FROM golang:1.19-alpine
WORKDIR /app

## Retrieve dependencies
COPY go.* ./
RUN go mod download

## Install Air
RUN apk add curl
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
RUN air init

COPY . ./

## Build application
RUN go build -v -o main

EXPOSE 8080

CMD ["air"]